[package]
name = "bitnn"
version = "0.1.0"
authors = ["Isaac Leonard <ifleonar@us.ibm.com>"]

[dependencies]
time = "0.1"
rand = "0.4.2"

[[bin]]
name = "onelayer"
path = "src/bin/onelayer.rs"

[[bin]]
name = "twolayer"
path = "src/bin/twolayer.rs"

[[bin]]
name = "conv"
path = "src/bin/conv.rs"

[[bin]]
name = "master"
path = "src/bin/master.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "macro_dense"
path = "src/bin/macro_dense.rs"
