[package]
name = "bitnn"
version = "0.1.0"
authors = ["Isaac Leonard <ifleonar@us.ibm.com>"]

[dependencies]
time = "0.1"
rand = "0.5"
image = "0.19.0"
rayon = "1.0"
serde = "1.0.79"
serde_derive = "1.0.76"
bincode = { version = "1.0.1", features = ["i128"] }
