[package]
name = "bitnn"
version = "0.1.0"
authors = ["Isaac Leonard <ifleonar@us.ibm.com>"]
edition = "2018"
description = "Greedy layerwise generation of ternary parameters for multi layer conv nets"
keywords = ["convolutional neural networks", "neural networks", "bitnets", "cifar10"]

[dependencies]
time = "0.1"
rayon = "1.2"
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.2", features = ["i128"] }
num_cpus = "1.11"
rand = "0.6"
rand_hc = "0.1.0"

[profile.release]
lto = true
