[package]
name = "bnn"
version = "0.2.0"
authors = ["Isaac Leonard <ifleonar@us.ibm.com>"]
edition = "2018"
description = "Greedy layerwise generation of ternary parameters for multi layer conv nets"
keywords = ["convolutional neural networks", "neural networks", "bitnets", "ternary", "cifar10"]

[dependencies]
time = "0.2"
rand = "0.7"
rand_hc = "0.2"
rand_distr = "0.3"
rand_core = "0.5"
rayon = "1.3"
num_cpus = "1.11"
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.2", features = ["i128"] }
criterion = "0.3"

[[bench]]
name = "bit_perf"
harness = false

[profile.bench]
codegen-units = 1
lto = "thin"

[profile.release]
#codegen-units = 1
#lto = "thin"
