[package]
name = "bitnn"
version = "0.1.0"
authors = ["Isaac Leonard <ifleonar@us.ibm.com>"]
edition = "2018"


[dependencies]
time = "0.1"
rand = "0.6"
rand_hc = "0.1.0"
rayon = "1.2"
serde = "1.0.79"
serde_derive = "1.0.76"
bincode = { version = "1.2", features = ["i128"] }
num_cpus = "1.11"

[profile.release]
lto = true
