[package]
name = "vulkano_demo"
version = "0.1.0"
authors = ["Isaac Leonard <isaac@isaacleonard.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11"
vulkano-shaders = "0.11"
rand = "0.6"
rand_hc = "0.1.0"
time = "0.1"
rayon = "1.0"
